name: Docker Image CI
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push image
      run: heroku container:push web -a excelcalc
    - name: Release to heroku
      run: heroku container:release web -a excelcalc
